package guitarsimulator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitarsimulator;
import  sun.audio.*;    //import the sun.audio package
import  java.io.*;
import org.jfugue.player.Player;

/**
 *
 * @author loganpeck
 */
public class guitarFin extends javax.swing.JFrame {
    Player guitar1 = new Player();
    Player beginningSong = new Player();
    /**
     * Creates new form guitarFin
     */
    public guitarFin() {
        initComponents();
//        beginningSong.play();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        programTitle = new javax.swing.JLabel();
        programSubtitle = new javax.swing.JLabel();
        eFlatBString = new javax.swing.JButton();
        aLowEString = new javax.swing.JButton();
        gSharpEString = new javax.swing.JButton();
        eBString = new javax.swing.JButton();
        thirdF = new javax.swing.JButton();
        bString = new javax.swing.JButton();
        firstGS = new javax.swing.JButton();
        bGString = new javax.swing.JButton();
        dAString = new javax.swing.JButton();
        secondC = new javax.swing.JButton();
        firstFS = new javax.swing.JButton();
        cSharpAString = new javax.swing.JButton();
        firstAS = new javax.swing.JButton();
        fSharpDString = new javax.swing.JButton();
        firstCS = new javax.swing.JButton();
        gDString = new javax.swing.JButton();
        aString = new javax.swing.JButton();
        secondAS = new javax.swing.JButton();
        dString = new javax.swing.JButton();
        firstB = new javax.swing.JButton();
        firstC = new javax.swing.JButton();
        thirdG = new javax.swing.JButton();
        firstG = new javax.swing.JButton();
        firstDS = new javax.swing.JButton();
        firstF = new javax.swing.JButton();
        secondFS = new javax.swing.JButton();
        aHighEString = new javax.swing.JButton();
        secondE = new javax.swing.JButton();
        secondD = new javax.swing.JButton();
        secondA = new javax.swing.JButton();
        secondF = new javax.swing.JButton();
        gString = new javax.swing.JButton();
        secondGSLowE = new javax.swing.JButton();
        lowEString = new javax.swing.JButton();
        cGString = new javax.swing.JButton();
        eString = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        programTitle.setFont(new java.awt.Font("Proxima Nova", 1, 24)); // NOI18N
        programTitle.setForeground(new java.awt.Color(255, 255, 255));
        programTitle.setText("Welcome to Guitar Simulator!");
        jPanel1.add(programTitle);
        programTitle.setBounds(310, 40, 370, 50);

        programSubtitle.setFont(new java.awt.Font("Roboto Slab", 0, 14)); // NOI18N
        programSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        programSubtitle.setText("Click on a note below to start playing");
        jPanel1.add(programSubtitle);
        programSubtitle.setBounds(340, 60, 290, 60);

        eFlatBString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        eFlatBString.setText("Eb");
        eFlatBString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eFlatBString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eFlatBStringActionPerformed(evt);
            }
        });
        jPanel1.add(eFlatBString);
        eFlatBString.setBounds(690, 270, 60, 29);

        aLowEString.setBackground(new java.awt.Color(102, 153, 255));
        aLowEString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        aLowEString.setForeground(new java.awt.Color(255, 255, 255));
        aLowEString.setText("A");
        aLowEString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aLowEString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLowEStringActionPerformed(evt);
            }
        });
        jPanel1.add(aLowEString);
        aLowEString.setBounds(810, 390, 60, 29);

        gSharpEString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        gSharpEString.setText("G#");
        gSharpEString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gSharpEString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSharpEStringActionPerformed(evt);
            }
        });
        jPanel1.add(gSharpEString);
        gSharpEString.setBounds(690, 240, 60, 29);

        eBString.setBackground(new java.awt.Color(255, 51, 102));
        eBString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        eBString.setForeground(new java.awt.Color(255, 255, 255));
        eBString.setText("E");
        eBString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eBString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBStringActionPerformed(evt);
            }
        });
        jPanel1.add(eBString);
        eBString.setBounds(810, 270, 60, 29);

        thirdF.setBackground(new java.awt.Color(0, 0, 0));
        thirdF.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        thirdF.setForeground(new java.awt.Color(255, 255, 255));
        thirdF.setText("F");
        thirdF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thirdF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdFActionPerformed(evt);
            }
        });
        jPanel1.add(thirdF);
        thirdF.setBounds(290, 240, 60, 29);

        bString.setBackground(new java.awt.Color(0, 204, 204));
        bString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        bString.setForeground(new java.awt.Color(255, 255, 255));
        bString.setText("B");
        bString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStringActionPerformed(evt);
            }
        });
        jPanel1.add(bString);
        bString.setBounds(190, 270, 40, 20);

        firstGS.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        firstGS.setText("G#");
        firstGS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstGSActionPerformed(evt);
            }
        });
        jPanel1.add(firstGS);
        firstGS.setBounds(290, 300, 60, 29);

        bGString.setBackground(new java.awt.Color(0, 204, 204));
        bGString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        bGString.setForeground(new java.awt.Color(255, 255, 255));
        bGString.setText("B");
        bGString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bGString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGStringActionPerformed(evt);
            }
        });
        jPanel1.add(bGString);
        bGString.setBounds(690, 300, 60, 29);

        dAString.setBackground(new java.awt.Color(255, 153, 51));
        dAString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        dAString.setForeground(new java.awt.Color(255, 255, 255));
        dAString.setText("D");
        dAString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dAString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dAStringActionPerformed(evt);
            }
        });
        jPanel1.add(dAString);
        dAString.setBounds(810, 360, 60, 29);

        secondC.setBackground(new java.awt.Color(0, 204, 102));
        secondC.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        secondC.setForeground(new java.awt.Color(255, 255, 255));
        secondC.setText("C");
        secondC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        secondC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondCActionPerformed(evt);
            }
        });
        jPanel1.add(secondC);
        secondC.setBounds(290, 270, 60, 29);

        firstFS.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        firstFS.setText("F#");
        firstFS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstFSActionPerformed(evt);
            }
        });
        jPanel1.add(firstFS);
        firstFS.setBounds(430, 390, 70, 29);

        cSharpAString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        cSharpAString.setText("C#");
        cSharpAString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cSharpAString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSharpAStringActionPerformed(evt);
            }
        });
        jPanel1.add(cSharpAString);
        cSharpAString.setBounds(690, 360, 60, 29);

        firstAS.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        firstAS.setText("A#");
        firstAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstASActionPerformed(evt);
            }
        });
        jPanel1.add(firstAS);
        firstAS.setBounds(290, 360, 60, 29);

        fSharpDString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        fSharpDString.setText("F#");
        fSharpDString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fSharpDString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSharpDStringActionPerformed(evt);
            }
        });
        jPanel1.add(fSharpDString);
        fSharpDString.setBounds(690, 330, 60, 29);

        firstCS.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        firstCS.setText("C#");
        firstCS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCSActionPerformed(evt);
            }
        });
        jPanel1.add(firstCS);
        firstCS.setBounds(430, 270, 70, 29);

        gDString.setBackground(new java.awt.Color(255, 255, 151));
        gDString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        gDString.setText("G");
        gDString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gDString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gDStringActionPerformed(evt);
            }
        });
        jPanel1.add(gDString);
        gDString.setBounds(810, 330, 60, 29);

        aString.setBackground(new java.awt.Color(102, 153, 255));
        aString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        aString.setForeground(new java.awt.Color(255, 255, 255));
        aString.setText("A");
        aString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aStringActionPerformed(evt);
            }
        });
        jPanel1.add(aString);
        aString.setBounds(190, 360, 40, 20);

        secondAS.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        secondAS.setText("Bb");
        secondAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        secondAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondASActionPerformed(evt);
            }
        });
        jPanel1.add(secondAS);
        secondAS.setBounds(560, 300, 60, 29);

        dString.setBackground(new java.awt.Color(255, 153, 51));
        dString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        dString.setForeground(new java.awt.Color(255, 255, 255));
        dString.setText("D");
        dString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dStringActionPerformed(evt);
            }
        });
        jPanel1.add(dString);
        dString.setBounds(190, 330, 40, 20);

        firstB.setBackground(new java.awt.Color(0, 204, 204));
        firstB.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        firstB.setForeground(new java.awt.Color(255, 255, 255));
        firstB.setText("B");
        firstB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstBActionPerformed(evt);
            }
        });
        jPanel1.add(firstB);
        firstB.setBounds(430, 360, 70, 29);

        firstC.setBackground(new java.awt.Color(0, 204, 102));
        firstC.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        firstC.setForeground(new java.awt.Color(255, 255, 255));
        firstC.setText("C");
        firstC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCActionPerformed(evt);
            }
        });
        jPanel1.add(firstC);
        firstC.setBounds(560, 360, 60, 29);

        thirdG.setBackground(new java.awt.Color(255, 255, 151));
        thirdG.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        thirdG.setText("G");
        thirdG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thirdG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdGActionPerformed(evt);
            }
        });
        jPanel1.add(thirdG);
        thirdG.setBounds(560, 240, 60, 29);

        firstG.setBackground(new java.awt.Color(255, 255, 151));
        firstG.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        firstG.setText("G");
        firstG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstGActionPerformed(evt);
            }
        });
        jPanel1.add(firstG);
        firstG.setBounds(560, 390, 60, 29);

        firstDS.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        firstDS.setText("Eb");
        firstDS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstDSActionPerformed(evt);
            }
        });
        jPanel1.add(firstDS);
        firstDS.setBounds(290, 330, 60, 29);

        firstF.setBackground(new java.awt.Color(0, 0, 0));
        firstF.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        firstF.setForeground(new java.awt.Color(255, 255, 255));
        firstF.setText("F");
        firstF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        firstF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstFActionPerformed(evt);
            }
        });
        jPanel1.add(firstF);
        firstF.setBounds(290, 390, 60, 29);

        secondFS.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        secondFS.setText("F#");
        secondFS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        secondFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondFSActionPerformed(evt);
            }
        });
        jPanel1.add(secondFS);
        secondFS.setBounds(430, 240, 70, 29);

        aHighEString.setBackground(new java.awt.Color(102, 153, 255));
        aHighEString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        aHighEString.setForeground(new java.awt.Color(255, 255, 255));
        aHighEString.setText("A");
        aHighEString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aHighEString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aHighEStringActionPerformed(evt);
            }
        });
        jPanel1.add(aHighEString);
        aHighEString.setBounds(810, 240, 60, 29);

        secondE.setBackground(new java.awt.Color(255, 51, 102));
        secondE.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        secondE.setForeground(new java.awt.Color(255, 255, 255));
        secondE.setText("E");
        secondE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        secondE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondEActionPerformed(evt);
            }
        });
        jPanel1.add(secondE);
        secondE.setBounds(430, 330, 70, 29);

        secondD.setBackground(new java.awt.Color(255, 153, 51));
        secondD.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        secondD.setForeground(new java.awt.Color(255, 255, 255));
        secondD.setText("D");
        secondD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        secondD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondDActionPerformed(evt);
            }
        });
        jPanel1.add(secondD);
        secondD.setBounds(560, 270, 60, 29);

        secondA.setBackground(new java.awt.Color(102, 153, 255));
        secondA.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        secondA.setForeground(new java.awt.Color(255, 255, 255));
        secondA.setText("A");
        secondA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        secondA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondAActionPerformed(evt);
            }
        });
        jPanel1.add(secondA);
        secondA.setBounds(430, 300, 70, 29);

        secondF.setBackground(new java.awt.Color(0, 0, 0));
        secondF.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        secondF.setForeground(new java.awt.Color(255, 255, 255));
        secondF.setText("F");
        secondF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        secondF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondFActionPerformed(evt);
            }
        });
        jPanel1.add(secondF);
        secondF.setBounds(560, 330, 60, 29);

        gString.setBackground(new java.awt.Color(255, 255, 151));
        gString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        gString.setText("G");
        gString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gStringActionPerformed(evt);
            }
        });
        jPanel1.add(gString);
        gString.setBounds(190, 300, 40, 20);

        secondGSLowE.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        secondGSLowE.setText("G#");
        secondGSLowE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        secondGSLowE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondGSLowEActionPerformed(evt);
            }
        });
        jPanel1.add(secondGSLowE);
        secondGSLowE.setBounds(690, 390, 60, 29);

        lowEString.setBackground(new java.awt.Color(255, 51, 102));
        lowEString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        lowEString.setForeground(new java.awt.Color(255, 255, 255));
        lowEString.setText("E");
        lowEString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lowEString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowEStringActionPerformed(evt);
            }
        });
        lowEString.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lowEStringKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lowEStringKeyPressed(evt);
            }
        });
        jPanel1.add(lowEString);
        lowEString.setBounds(190, 390, 40, 20);

        cGString.setBackground(new java.awt.Color(0, 204, 102));
        cGString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        cGString.setForeground(new java.awt.Color(255, 255, 255));
        cGString.setText("C");
        cGString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cGString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cGStringActionPerformed(evt);
            }
        });
        jPanel1.add(cGString);
        cGString.setBounds(810, 300, 60, 29);

        eString.setBackground(new java.awt.Color(255, 51, 102));
        eString.setFont(new java.awt.Font("Proxima Nova", 1, 13)); // NOI18N
        eString.setForeground(new java.awt.Color(255, 255, 255));
        eString.setText("E");
        eString.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eString.setRolloverEnabled(true);
        eString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eStringActionPerformed(evt);
            }
        });
        jPanel1.add(eString);
        eString.setBounds(190, 240, 40, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/guitar_background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] E5");
    }//GEN-LAST:event_eStringActionPerformed

    private void thirdFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdFActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F5");
    }//GEN-LAST:event_thirdFActionPerformed

    private void secondFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondFSActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F#5");
    }//GEN-LAST:event_secondFSActionPerformed

    private void thirdGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdGActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G5");
    }//GEN-LAST:event_thirdGActionPerformed

    private void gSharpEStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSharpEStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G#5");
    }//GEN-LAST:event_gSharpEStringActionPerformed

    private void aHighEStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aHighEStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A6");
    }//GEN-LAST:event_aHighEStringActionPerformed

    private void eBStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] E5");
    }//GEN-LAST:event_eBStringActionPerformed

    private void eFlatBStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eFlatBStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] Eb5");
    }//GEN-LAST:event_eFlatBStringActionPerformed

    private void secondDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondDActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] D5");
    }//GEN-LAST:event_secondDActionPerformed

    private void firstCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCSActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] C#5");
    }//GEN-LAST:event_firstCSActionPerformed

    private void secondCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondCActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] C5");
    }//GEN-LAST:event_secondCActionPerformed

    private void bStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] B4");
    }//GEN-LAST:event_bStringActionPerformed

    private void gStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G4");
    }//GEN-LAST:event_gStringActionPerformed

    private void firstGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstGSActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G#4");
    }//GEN-LAST:event_firstGSActionPerformed

    private void secondAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondAActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A4");
    }//GEN-LAST:event_secondAActionPerformed

    private void secondASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondASActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A#4");
    }//GEN-LAST:event_secondASActionPerformed

    private void bGStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] B4");
    }//GEN-LAST:event_bGStringActionPerformed

    private void cGStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cGStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] C5");
    }//GEN-LAST:event_cGStringActionPerformed

    private void gDStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gDStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G4");
    }//GEN-LAST:event_gDStringActionPerformed

    private void fSharpDStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSharpDStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F#4");
    }//GEN-LAST:event_fSharpDStringActionPerformed

    private void secondFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondFActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F4");
    }//GEN-LAST:event_secondFActionPerformed

    private void secondEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondEActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] E4");
    }//GEN-LAST:event_secondEActionPerformed

    private void firstDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstDSActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] D#4");
    }//GEN-LAST:event_firstDSActionPerformed

    private void dStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] D4");
    }//GEN-LAST:event_dStringActionPerformed

    private void aStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A3");
    }//GEN-LAST:event_aStringActionPerformed

    private void firstASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstASActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A#3");
    }//GEN-LAST:event_firstASActionPerformed

    private void firstBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstBActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] B3");
    }//GEN-LAST:event_firstBActionPerformed

    private void firstCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] C4");
    }//GEN-LAST:event_firstCActionPerformed

    private void cSharpAStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSharpAStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] C#4");
    }//GEN-LAST:event_cSharpAStringActionPerformed

    private void dAStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dAStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] D4");
    }//GEN-LAST:event_dAStringActionPerformed

    private void aLowEStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLowEStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A3");
    }//GEN-LAST:event_aLowEStringActionPerformed

    private void secondGSLowEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondGSLowEActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G#3");
    }//GEN-LAST:event_secondGSLowEActionPerformed

    private void firstGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstGActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G3");
    }//GEN-LAST:event_firstGActionPerformed

    private void firstFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstFSActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F#3");
    }//GEN-LAST:event_firstFSActionPerformed

    private void firstFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstFActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F3");
    }//GEN-LAST:event_firstFActionPerformed

    private void lowEStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowEStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] E3");
    }//GEN-LAST:event_lowEStringActionPerformed

    private void lowEStringKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lowEStringKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_lowEStringKeyTyped

    private void lowEStringKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lowEStringKeyPressed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] E3");
    }//GEN-LAST:event_lowEStringKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guitarFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guitarFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guitarFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guitarFin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guitarFin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aHighEString;
    private javax.swing.JButton aLowEString;
    private javax.swing.JButton aString;
    private javax.swing.JButton bGString;
    private javax.swing.JButton bString;
    private javax.swing.JButton cGString;
    private javax.swing.JButton cSharpAString;
    private javax.swing.JButton dAString;
    private javax.swing.JButton dString;
    private javax.swing.JButton eBString;
    private javax.swing.JButton eFlatBString;
    private javax.swing.JButton eString;
    private javax.swing.JButton fSharpDString;
    private javax.swing.JButton firstAS;
    private javax.swing.JButton firstB;
    private javax.swing.JButton firstC;
    private javax.swing.JButton firstCS;
    private javax.swing.JButton firstDS;
    private javax.swing.JButton firstF;
    private javax.swing.JButton firstFS;
    private javax.swing.JButton firstG;
    private javax.swing.JButton firstGS;
    private javax.swing.JButton gDString;
    private javax.swing.JButton gSharpEString;
    private javax.swing.JButton gString;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lowEString;
    private javax.swing.JLabel programSubtitle;
    private javax.swing.JLabel programTitle;
    private javax.swing.JButton secondA;
    private javax.swing.JButton secondAS;
    private javax.swing.JButton secondC;
    private javax.swing.JButton secondD;
    private javax.swing.JButton secondE;
    private javax.swing.JButton secondF;
    private javax.swing.JButton secondFS;
    private javax.swing.JButton secondGSLowE;
    private javax.swing.JButton thirdF;
    private javax.swing.JButton thirdG;
    // End of variables declaration//GEN-END:variables
}
