/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guitarsimulator;
import  sun.audio.*;    //import the sun.audio package
import  java.io.*;
import org.jfugue.player.Player;

/**
 *
 * @author loganpeck
 */
public class guitarTypeOne extends javax.swing.JFrame {
    Player guitar1 = new Player();
    Player guitar2 = new Player();
    Player guitar3 = new Player();
    /**
     * Creates new form guitarTypeOne
     */
    public guitarTypeOne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstDS = new javax.swing.JButton();
        firstAS = new javax.swing.JButton();
        secondC = new javax.swing.JButton();
        thirdF = new javax.swing.JButton();
        firstGS = new javax.swing.JButton();
        firstF = new javax.swing.JButton();
        secondFS = new javax.swing.JButton();
        thirdG = new javax.swing.JButton();
        firstCS = new javax.swing.JButton();
        secondA = new javax.swing.JButton();
        secondE = new javax.swing.JButton();
        firstB = new javax.swing.JButton();
        firstFS = new javax.swing.JButton();
        secondD = new javax.swing.JButton();
        secondAS = new javax.swing.JButton();
        secondF = new javax.swing.JButton();
        firstC = new javax.swing.JButton();
        firstG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        secondGSLowE = new javax.swing.JButton();
        cSharpAString = new javax.swing.JButton();
        fSharpDString = new javax.swing.JButton();
        bGString = new javax.swing.JButton();
        eFlatBString = new javax.swing.JButton();
        gSharpEString = new javax.swing.JButton();
        aLowEString = new javax.swing.JButton();
        dAString = new javax.swing.JButton();
        gDString = new javax.swing.JButton();
        cGString = new javax.swing.JButton();
        eBString = new javax.swing.JButton();
        aHighEString = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        lowEString = new javax.swing.JButton();
        aString = new javax.swing.JButton();
        dString = new javax.swing.JButton();
        gString = new javax.swing.JButton();
        bString = new javax.swing.JButton();
        eString = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        firstDS.setText("Eb");
        firstDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstDSActionPerformed(evt);
            }
        });

        firstAS.setText("A#");
        firstAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstASActionPerformed(evt);
            }
        });

        secondC.setText("C");
        secondC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondCActionPerformed(evt);
            }
        });

        thirdF.setText("F");
        thirdF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdFActionPerformed(evt);
            }
        });

        firstGS.setText("G#");
        firstGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstGSActionPerformed(evt);
            }
        });

        firstF.setText("F");
        firstF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstFActionPerformed(evt);
            }
        });

        secondFS.setText("F#");
        secondFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondFSActionPerformed(evt);
            }
        });

        thirdG.setText("G");
        thirdG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdGActionPerformed(evt);
            }
        });

        firstCS.setText("C#");
        firstCS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCSActionPerformed(evt);
            }
        });

        secondA.setText("A");
        secondA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondAActionPerformed(evt);
            }
        });

        secondE.setText("E");
        secondE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondEActionPerformed(evt);
            }
        });

        firstB.setText("B");
        firstB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstBActionPerformed(evt);
            }
        });

        firstFS.setText("F#");
        firstFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstFSActionPerformed(evt);
            }
        });

        secondD.setText("D");
        secondD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondDActionPerformed(evt);
            }
        });

        secondAS.setText("A#");
        secondAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondASActionPerformed(evt);
            }
        });

        secondF.setText("F");
        secondF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondFActionPerformed(evt);
            }
        });

        firstC.setText("C");
        firstC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstCActionPerformed(evt);
            }
        });

        firstG.setText("G");
        firstG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstGActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("B");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("G");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("D");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("A");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E");

        jLabel7.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Welcome to Guitar Simulator!");

        secondGSLowE.setText("G#");
        secondGSLowE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondGSLowEActionPerformed(evt);
            }
        });

        cSharpAString.setText("C#");
        cSharpAString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cSharpAStringActionPerformed(evt);
            }
        });

        fSharpDString.setText("F#");
        fSharpDString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSharpDStringActionPerformed(evt);
            }
        });

        bGString.setText("B");
        bGString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGStringActionPerformed(evt);
            }
        });

        eFlatBString.setText("Eb");
        eFlatBString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eFlatBStringActionPerformed(evt);
            }
        });

        gSharpEString.setText("G#");
        gSharpEString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSharpEStringActionPerformed(evt);
            }
        });

        aLowEString.setText("A");
        aLowEString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aLowEStringActionPerformed(evt);
            }
        });

        dAString.setText("D");
        dAString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dAStringActionPerformed(evt);
            }
        });

        gDString.setText("G");
        gDString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gDStringActionPerformed(evt);
            }
        });

        cGString.setText("C");
        cGString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cGStringActionPerformed(evt);
            }
        });

        eBString.setText("E");
        eBString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBStringActionPerformed(evt);
            }
        });

        aHighEString.setText("A");
        aHighEString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aHighEStringActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Slab", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Choose your guitar by selecting the checkbox below");

        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("jCheckBox1");

        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("jCheckBox2");

        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setText("jCheckBox3");

        lowEString.setText("E");
        lowEString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowEStringActionPerformed(evt);
            }
        });
        lowEString.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lowEStringKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lowEStringKeyPressed(evt);
            }
        });

        aString.setText("A");
        aString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aStringActionPerformed(evt);
            }
        });

        dString.setText("D");
        dString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dStringActionPerformed(evt);
            }
        });

        gString.setText("G");
        gString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gStringActionPerformed(evt);
            }
        });

        bString.setText("B");
        bString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStringActionPerformed(evt);
            }
        });

        eString.setText("E");
        eString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eStringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lowEString)
                            .addComponent(aString)
                            .addComponent(dString)
                            .addComponent(gString)
                            .addComponent(bString)
                            .addComponent(eString))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thirdF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondC, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstGS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstDS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstAS, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstFS, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondFS, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstCS, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondA, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(secondE, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstB, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jCheckBox1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(secondF, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fSharpDString, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gDString, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstG, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondGSLowE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aLowEString, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstC, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cSharpAString, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dAString, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(thirdG, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(gSharpEString, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(aHighEString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(secondD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eFlatBString, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eBString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(secondAS, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bGString, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cGString, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox2)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox3)))
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(323, 323, 323))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eString, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(thirdF)
                        .addComponent(secondFS)
                        .addComponent(thirdG)
                        .addComponent(jLabel1)
                        .addComponent(gSharpEString)
                        .addComponent(aHighEString)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bString, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(secondC)
                        .addComponent(firstCS)
                        .addComponent(secondD)
                        .addComponent(jLabel2)
                        .addComponent(eFlatBString)
                        .addComponent(eBString)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gString)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstGS)
                        .addComponent(secondA)
                        .addComponent(secondAS)
                        .addComponent(jLabel3)
                        .addComponent(bGString)
                        .addComponent(cGString)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dString)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstDS)
                        .addComponent(secondE)
                        .addComponent(secondF)
                        .addComponent(jLabel4)
                        .addComponent(fSharpDString)
                        .addComponent(gDString)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aString, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(firstAS)
                        .addComponent(firstB)
                        .addComponent(firstC)
                        .addComponent(jLabel5)
                        .addComponent(cSharpAString)
                        .addComponent(dAString)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstF)
                    .addComponent(firstFS)
                    .addComponent(firstG)
                    .addComponent(jLabel6)
                    .addComponent(secondGSLowE)
                    .addComponent(aLowEString)
                    .addComponent(lowEString))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstGActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G3");
    }//GEN-LAST:event_firstGActionPerformed

    private void firstCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] C4");
    }//GEN-LAST:event_firstCActionPerformed

    private void secondFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondFActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F4");
    }//GEN-LAST:event_secondFActionPerformed

    private void secondASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondASActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A#4");
    }//GEN-LAST:event_secondASActionPerformed

    private void firstFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstFSActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F#3");
    }//GEN-LAST:event_firstFSActionPerformed

    private void firstBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstBActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] B3");
    }//GEN-LAST:event_firstBActionPerformed

    private void secondEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondEActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] E4");
    }//GEN-LAST:event_secondEActionPerformed

    private void secondAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondAActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A4");
    }//GEN-LAST:event_secondAActionPerformed

    private void firstCSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstCSActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] C#5");
    }//GEN-LAST:event_firstCSActionPerformed

    private void firstFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstFActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F3");

    }//GEN-LAST:event_firstFActionPerformed

    private void firstGSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstGSActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G#4");
    }//GEN-LAST:event_firstGSActionPerformed

    private void secondCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondCActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] C5");
    }//GEN-LAST:event_secondCActionPerformed

    private void firstASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstASActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A#3");
    }//GEN-LAST:event_firstASActionPerformed

    private void firstDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstDSActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] D#4");
    }//GEN-LAST:event_firstDSActionPerformed

    private void secondGSLowEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondGSLowEActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G#3");
    }//GEN-LAST:event_secondGSLowEActionPerformed

    private void secondDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondDActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] D5");
    }//GEN-LAST:event_secondDActionPerformed

    private void thirdGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdGActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G5");
    }//GEN-LAST:event_thirdGActionPerformed

    private void secondFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondFSActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F#5");
    }//GEN-LAST:event_secondFSActionPerformed

    private void thirdFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdFActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F5");
    }//GEN-LAST:event_thirdFActionPerformed

    private void cSharpAStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cSharpAStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] C#4");
    }//GEN-LAST:event_cSharpAStringActionPerformed

    private void fSharpDStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSharpDStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] F#4");
    }//GEN-LAST:event_fSharpDStringActionPerformed

    private void bGStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] B4");
    }//GEN-LAST:event_bGStringActionPerformed

    private void eFlatBStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eFlatBStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] Eb5");
    }//GEN-LAST:event_eFlatBStringActionPerformed

    private void gSharpEStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSharpEStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G#5");
    }//GEN-LAST:event_gSharpEStringActionPerformed

    private void aLowEStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLowEStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A3");
    }//GEN-LAST:event_aLowEStringActionPerformed

    private void dAStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dAStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] D4");
    }//GEN-LAST:event_dAStringActionPerformed

    private void gDStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gDStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G4");
    }//GEN-LAST:event_gDStringActionPerformed

    private void cGStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cGStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] C5");
    }//GEN-LAST:event_cGStringActionPerformed

    private void eBStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] E5");
    }//GEN-LAST:event_eBStringActionPerformed

    private void aHighEStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aHighEStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A6");
    }//GEN-LAST:event_aHighEStringActionPerformed

    private void eStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] E5");
    }//GEN-LAST:event_eStringActionPerformed

    private void lowEStringKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lowEStringKeyPressed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] E3");
    }//GEN-LAST:event_lowEStringKeyPressed

    private void lowEStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowEStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] E3");
    }//GEN-LAST:event_lowEStringActionPerformed

    private void aStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] A3");
    }//GEN-LAST:event_aStringActionPerformed

    private void dStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] D4");
    }//GEN-LAST:event_dStringActionPerformed

    private void gStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] G4");
    }//GEN-LAST:event_gStringActionPerformed

    private void bStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStringActionPerformed
        // TODO add your handling code here:
        guitar1.play("V0 I[Guitar] B4");
    }//GEN-LAST:event_bStringActionPerformed

    private void lowEStringKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lowEStringKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lowEStringKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guitarTypeOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guitarTypeOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guitarTypeOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guitarTypeOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guitarTypeOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aHighEString;
    private javax.swing.JButton aLowEString;
    private javax.swing.JButton aString;
    private javax.swing.JButton bGString;
    private javax.swing.JButton bString;
    private javax.swing.JButton cGString;
    private javax.swing.JButton cSharpAString;
    private javax.swing.JButton dAString;
    private javax.swing.JButton dString;
    private javax.swing.JButton eBString;
    private javax.swing.JButton eFlatBString;
    private javax.swing.JButton eString;
    private javax.swing.JButton fSharpDString;
    private javax.swing.JButton firstAS;
    private javax.swing.JButton firstB;
    private javax.swing.JButton firstC;
    private javax.swing.JButton firstCS;
    private javax.swing.JButton firstDS;
    private javax.swing.JButton firstF;
    private javax.swing.JButton firstFS;
    private javax.swing.JButton firstG;
    private javax.swing.JButton firstGS;
    private javax.swing.JButton gDString;
    private javax.swing.JButton gSharpEString;
    private javax.swing.JButton gString;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lowEString;
    private javax.swing.JButton secondA;
    private javax.swing.JButton secondAS;
    private javax.swing.JButton secondC;
    private javax.swing.JButton secondD;
    private javax.swing.JButton secondE;
    private javax.swing.JButton secondF;
    private javax.swing.JButton secondFS;
    private javax.swing.JButton secondGSLowE;
    private javax.swing.JButton thirdF;
    private javax.swing.JButton thirdG;
    // End of variables declaration//GEN-END:variables
}
